# Generated by Django 5.0.2 on 2025-06-22 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('content', models.TextField(verbose_name='Содержание отчета')),
                ('report_type', models.CharField(choices=[('comprehensive', 'Комплексный'), ('sales', 'По продажам'), ('products', 'По продуктам'), ('customers', 'По клиентам')], max_length=20, verbose_name='Тип отчета')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-generated_at'],
            },
        ),
    ]
