# Generated by Django 5.0.2 on 2025-06-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='last_trained',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обучение'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='algorithm',
            field=models.CharField(choices=[('random_forest', 'Random Forest'), ('linear_regression', 'Linear Regression'), ('logistic_regression', 'Logistic Regression'), ('kmeans', 'K-Means'), ('svm', 'Support Vector Machine'), ('neural_network', 'Neural Network')], max_length=100, verbose_name='Алгоритм'),
        ),
    ]
