# Generated by Django 5.0.2 on 2025-06-23 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_traininghistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(verbose_name='Входные данные')),
                ('prediction', models.CharField(max_length=255, verbose_name='Результат прогноза')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прогноза')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to='analytics.mlmodel', verbose_name='Модель')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История прогноза',
                'verbose_name_plural': 'История прогнозов',
                'ordering': ['-created_at'],
            },
        ),
    ]
